<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>pmlog</string>
    <string>pm_log</string>
   </array>
  <key>name</key>
  <string>pagemodellog</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.pagemodellog</string>
  <key>uuid</key>
  <string>41ff3e9e-d77c-44bc-8c6b-92f358244f94</string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(Starting test:.*)</string>
          <key>name</key>
          <string>entity.name.pagemodellog</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(^\[[0-9\x{003a}.]*\] )</string>
          <key>name</key>
          <string>text.pagemodellog</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(Assert|Execute)( javaScript )(\[)(.*)(\])( on page:)(\[)(.*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>9</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Waiting for page, )(.*)( to display.)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(test page model \[)([^\]]*)(\] from page \[)([^\]]*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Testing page model \[)([^\]]*)(\] from page \[)([^\]]*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Sleeping )([0-9]*)( [a-z]*\.)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Refreshing page \[[^\]]*\] after wait.)</string>
          <key>name</key>
          <string>text.pagemodellog</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(Inserting &lt;div id=&apos;refresh-.*&apos;/&gt; to verify page refresh\.)</string>
          <key>name</key>
          <string>text.pagemodellog</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(Expecting no redirect: on page \[[^\]]*\])</string>
          <key>name</key>
          <string>text.pagemodellog</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(Using chromedriver )([0-9.]*)( .*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.special-method.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Exporting webdriver.chrome.drive.*)</string>
          <key>name</key>
          <string>text.pagemodellog</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(Opening url \[)(.*)(\] with capablities: )(.*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.special-method.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>keyword.other.special-method.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Assert|Execute|Find)( wait for | wait and refresh for )?([^\x{003a}]*: )([a-zA-Z]*: ?)?(element\(by\(.*\), found\(.*\)\))( on page \[)(.*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.special-method.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>support.function.pagemodellog</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Assert|Execute|Find)( wait for | wait and refresh for )?([^\x{003a}]*: )([a-zA-Z]*:)( to |, )?(element\(by\(.*\), found\(.*\)\))( on page \[)(.*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.special-method.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>support.function.pagemodellog</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>9</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Assert|Execute|Find)( wait for | wait and refresh for )?([^\x{003a}]*: )([a-zA-Z]*:)?(\[)(.*)(\])( to |, )(element\(by\(.*\), found\(.*\)\))( on page \[)(.*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.special-method.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>9</key>
            <dict>
              <key>name</key>
              <string>support.function.pagemodellog</string>
            </dict>
            <key>10</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>11</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>12</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Assert|Execute|Find)( wait for | wait and refresh for )?([^\x{003a}]*: )(\[)(.*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.special-method.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(element\(by\(.*\), found\(.*\)\))( on page \[)(.*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>support.function.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Assert)( wait for | wait and refresh for)?( \[)(.*)(\] )([a-zA-Z0-9\x{0020}]*)( \[)(.*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.special-method.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>9</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Assert)( \[)(.*)(\] )(is empty)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Storing)(: key:\[)(.*)(\], value:\[)(.*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Assert Loading)(: key:\[)(.*)(\], value:\[)(.*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Assert Removing)(: key:\[)(.*)(\], value:\[)(.*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Test Failure:|org.pagemodel.web.utils.PageException:)</string>
          <key>name</key>
          <string>invalid.pagemodellog</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(^\s*at)( )(org\.openqa|org\.gradle|org\.junit|java|sun|com.sun)(\.[a-zA-Z0-9\.\x{0024}]*)(\()(.*|[a-zA-Z0-9]*\.java:[0-9]*)(\))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>invalid.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>comment.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>comment.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>comment.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>comment.pagemodellog</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>comment.pagemodellog</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>comment.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(^\s*at)( )(org\.pagemodel)(\.[a-zA-Z0-9\.\x{0024}]*)(\()(.*|[a-zA-Z0-9]*\.java)(:)([0-9]*)(\))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>invalid.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.pagemodellog</string>
            </dict>
            <key>9</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(^\s*at)( [a-zA-Z0-9.\x{0024}]*)(\()(.*|[a-zA-Z0-9]*\.java)(:)([0-9]*)(\))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>invalid.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.special-method.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.pagemodellog</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Executing)( SSH command )(\[)(.*)(\])</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.pagemodellog</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>string.pagemodellog</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(Connecting to SSH.*)</string>
          <key>name</key>
          <string>text.pagemodellog</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(Disconnecting from SSH.*)</string>
          <key>name</key>
          <string>text.pagemodellog</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(SSH )([a-zA-Z0-9\x{0020}.\x{002c}]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.pagemodellog</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.other.special-method.pagemodellog</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(ChromeDriver was started successfully.)</string>
          <key>name</key>
          <string>text.pagemodellog</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.*org.openqa.selenium.remote.ProtocolHandshake.*)</string>
          <key>name</key>
          <string>text.pagemodellog</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(INFO: Detected dialect: W3C)</string>
          <key>name</key>
          <string>text.pagemodellog</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.pagemodellog</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
